import logging
import plistlib
from pathlib import Path

import pytest

from piforge.core import PiForgeError, ToolNotFoundError
from piforge.fab import slicer
from piforge.fab.slicer import (
    SliceResult,
    SlicerInfo,
    SlicerNotFoundError,
    find_slicer,
    parse_gcode_stats,
    slice_stl,
)

# Stand-in for the PrusaSlicer CLI: answers --help with a version banner, otherwise records its
# argv (one per line) next to itself and writes a small G-code file to --output.
FAKE_PRUSA = r"""#!/bin/sh
here="${0%/*}"  # no external commands: PATH holds only this folder
out=""
case "$1" in --help) echo "PrusaSlicer-2.8.1+MacOS-arm64 based on Slic3r"; exit 0 ;; esac
printf '%s\n' "$@" > "$here/argv.txt"
while [ $# -gt 0 ]; do
  case "$1" in --output) out="$2"; shift ;; esac
  shift
done
printf '; generated by PrusaSlicer 2.8.1\nG1 X0\n; filament used [mm] = 1234.5\n; total filament used [g] = 3.70\n; estimated printing time (normal mode) = 12m 3s\n' > "$out"
echo "Slicing result exported to $out"
"""

# Stand-in for the OrcaSlicer / Bambu Studio CLI: writes plate_1.gcode into --outputdir.
FAKE_ORCA = r"""#!/bin/sh
here="${0%/*}"  # no external commands: PATH holds only this folder
outdir=""
case "$1" in --help) echo "OrcaSlicer-2.2.0 command line"; exit 0 ;; esac
printf '%s\n' "$@" > "$here/argv.txt"
while [ $# -gt 0 ]; do
  case "$1" in --outputdir) outdir="$2"; shift ;; esac
  shift
done
printf '; HEADER_BLOCK_START\n; model printing time: 20m 0s; total estimated time: 25m 0s\n; total filament length [mm] : 2000.0\n; total filament weight [g] : 6.10\n; HEADER_BLOCK_END\nG1 X0\n' > "$outdir/plate_1.gcode"
"""

FAKE_BROKEN = r"""#!/bin/sh
case "$1" in --help) echo "PrusaSlicer-2.8.1"; exit 0 ;; esac
echo "error: object is not manifold" >&2
exit 3
"""

FAKE_SILENT = r"""#!/bin/sh
case "$1" in --help) echo "PrusaSlicer-2.8.1"; exit 0 ;; esac
exit 0
"""

FAKE_ORCA_SILENT = r"""#!/bin/sh
case "$1" in --help) echo "OrcaSlicer-2.2.0"; exit 0 ;; esac
exit 0
"""


def _install(directory: Path, name: str, script: str) -> Path:
    directory.mkdir(parents=True, exist_ok=True)
    exe = directory / name
    exe.write_text(script)
    exe.chmod(0o755)
    return exe


@pytest.fixture
def no_slicers(monkeypatch, tmp_path):
    """Hide every real slicer: empty PATH, no app folders, no PIFORGE_SLICER override."""
    empty = tmp_path / "empty-bin"
    empty.mkdir()
    monkeypatch.setenv("PATH", str(empty))
    monkeypatch.delenv("PIFORGE_SLICER", raising=False)
    monkeypatch.setattr(slicer, "APP_DIRS", (tmp_path / "no-apps",))
    return empty


@pytest.fixture
def stl(spaced_tmp):
    path = spaced_tmp / "my part.stl"
    path.write_text("solid part\nendsolid part\n")
    return path


def test_slicer_absent(no_slicers, stl, spaced_tmp):
    assert find_slicer() is None
    with pytest.raises(SlicerNotFoundError) as excinfo:
        slice_stl(stl, "generic", "PLA", spaced_tmp / "out")
    assert isinstance(excinfo.value, ToolNotFoundError)
    assert isinstance(excinfo.value, PiForgeError)
    assert "PrusaSlicer" in str(excinfo.value)


def test_find_slicer_on_path(no_slicers, monkeypatch, spaced_tmp):
    exe = _install(spaced_tmp / "bin", "prusa-slicer", FAKE_PRUSA)
    monkeypatch.setenv("PATH", str(exe.parent))
    info = find_slicer()
    assert isinstance(info, SlicerInfo)
    assert (info.name, Path(info.path), info.version) == ("PrusaSlicer", exe, "2.8.1")


def test_find_slicer_in_applications(no_slicers, monkeypatch, spaced_tmp):
    apps = spaced_tmp / "Applications"
    bundle = apps / "OrcaSlicer.app" / "Contents"
    exe = _install(bundle / "MacOS", "OrcaSlicer", FAKE_ORCA)
    (bundle / "Info.plist").write_bytes(plistlib.dumps({"CFBundleShortVersionString": "2.2.0"}))
    monkeypatch.setattr(slicer, "APP_DIRS", (apps,))
    info = find_slicer()
    assert (info.name, Path(info.path), info.version) == ("OrcaSlicer", exe, "2.2.0")


def test_slice_stl_with_prusa_cli(no_slicers, monkeypatch, spaced_tmp, stl):
    exe = _install(spaced_tmp / "bin", "prusa-slicer", FAKE_PRUSA)
    monkeypatch.setenv("PATH", str(exe.parent))
    out_dir = spaced_tmp / "out dir"
    res = slice_stl(stl, "prusa_mk4", "PETG", out_dir, infill=0.2, supports=True)
    assert isinstance(res, SliceResult)
    assert res.gcode_path == out_dir / "my part.gcode" and res.gcode_path.is_file()
    assert res.time_s == 723 and res.filament_g == pytest.approx(3.70)
    assert res.filament_m == pytest.approx(1.2345)
    assert res.settings_applied
    assert "exported" in res.log
    argv = (exe.parent / "argv.txt").read_text().splitlines()
    assert argv[-1] == str(stl) and "--export-gcode" in argv

    def opt(name):
        return argv[argv.index(name) + 1]

    assert opt("--output") == str(out_dir / "my part.gcode")
    assert opt("--fill-density") == "20%"
    assert opt("--bed-shape") == "0x0,250x0,250x210,0x210"  # prusa_mk4 bed
    assert opt("--max-print-height") == "220"
    assert opt("--layer-height") == "0.2" and opt("--nozzle-diameter") == "0.4"
    assert opt("--filament-density") == "1.27"  # PETG
    assert "--support-material" in argv


def test_slice_stl_without_supports(no_slicers, monkeypatch, spaced_tmp, stl):
    exe = _install(spaced_tmp / "bin", "prusa-slicer", FAKE_PRUSA)
    monkeypatch.setenv("PATH", str(exe.parent))
    slice_stl(stl, "generic", "PLA", spaced_tmp / "out", supports=False)
    argv = (exe.parent / "argv.txt").read_text().splitlines()
    assert "--support-material" not in argv
    assert argv[argv.index("--fill-density") + 1] == "15%"


def test_slice_stl_with_orca_cli_via_env(no_slicers, monkeypatch, spaced_tmp, stl, caplog):
    exe = _install(spaced_tmp / "tools", "orca-slicer", FAKE_ORCA)
    monkeypatch.setenv("PIFORGE_SLICER", str(exe))
    assert find_slicer().name == "OrcaSlicer"
    out_dir = spaced_tmp / "orca out"
    with caplog.at_level(logging.WARNING, logger="piforge.fab.slicer"):
        res = slice_stl(stl, "bambu_p1s", "PLA", out_dir)
    # Orca/Bambu CLIs take no per-option overrides: the stats describe the slicer's own profile
    assert res.settings_applied is False
    assert any("not applied" in r.getMessage() for r in caplog.records if r.levelno == logging.WARNING)
    assert res.gcode_path == out_dir / "plate_1.gcode"
    assert res.time_s == 25 * 60 and res.filament_g == pytest.approx(6.10)
    assert res.filament_m == pytest.approx(2.0)
    argv = (exe.parent / "argv.txt").read_text().splitlines()
    assert argv[:2] == ["--slice", "0"] and argv[argv.index("--outputdir") + 1] == str(out_dir)
    assert argv[-1] == str(stl)


@pytest.mark.parametrize("kwargs", [{"infill": 0.4}, {"supports": True}])
def test_orca_rejects_settings_it_cannot_apply(no_slicers, monkeypatch, spaced_tmp, stl, kwargs):
    monkeypatch.setenv("PIFORGE_SLICER", str(_install(spaced_tmp / "tools", "orca-slicer", FAKE_ORCA)))
    with pytest.raises(PiForgeError, match="--load-settings"):
        slice_stl(stl, "bambu_p1s", "PLA", spaced_tmp / "out", **kwargs)


def test_orca_filament_profile_alone_cannot_carry_infill(no_slicers, monkeypatch, spaced_tmp, stl):
    # infill and supports live in the process profile (--load-settings); a filament file has neither
    monkeypatch.setenv("PIFORGE_SLICER", str(_install(spaced_tmp / "tools", "orca-slicer", FAKE_ORCA)))
    with pytest.raises(PiForgeError, match="--load-settings"):
        slice_stl(stl, "bambu_p1s", "PLA", spaced_tmp / "out", infill=0.4,
                  extra_args=["--load-filaments", "pla.json"])


def test_orca_with_profiles_takes_settings_from_them(no_slicers, monkeypatch, spaced_tmp, stl):
    exe = _install(spaced_tmp / "tools", "orca-slicer", FAKE_ORCA)
    monkeypatch.setenv("PIFORGE_SLICER", str(exe))
    profiles = ["--load-settings", "machine.json;process.json", "--load-filaments", "pla.json"]
    res = slice_stl(stl, "bambu_p1s", "PLA", spaced_tmp / "out", infill=0.4, extra_args=profiles)
    assert res.settings_applied is False  # the profiles decide, not infill=0.4
    argv = (exe.parent / "argv.txt").read_text().splitlines()
    assert argv[argv.index("--load-settings") + 1] == "machine.json;process.json"


def test_orca_never_returns_stale_plate_gcode(no_slicers, monkeypatch, spaced_tmp, stl):
    monkeypatch.setenv("PIFORGE_SLICER",
                       str(_install(spaced_tmp / "tools", "orca-slicer", FAKE_ORCA_SILENT)))
    out_dir = spaced_tmp / "out"
    out_dir.mkdir()
    (out_dir / "plate_1.gcode").write_text("; total estimated time: 9h 0m 0s\n"
                                           "; total filament weight [g] : 999\n")
    keep = out_dir / "notes.gcode"  # not a slicer output name: must survive untouched
    keep.write_text("; my notes\n")
    with pytest.raises(PiForgeError, match="no G-code"):
        slice_stl(stl, "bambu_p1s", "PLA", out_dir)
    assert not (out_dir / "plate_1.gcode").exists()  # stale output cleared before slicing
    assert keep.read_text() == "; my notes\n"


def test_output_dir_that_is_a_file_is_rejected(spaced_tmp, stl):
    not_a_dir = spaced_tmp / "out"
    not_a_dir.write_text("I am a file")
    with pytest.raises(PiForgeError, match="not a directory"):
        slice_stl(stl, "generic", "PLA", not_a_dir)


def test_slicer_failure_raises_with_log(no_slicers, monkeypatch, spaced_tmp, stl):
    exe = _install(spaced_tmp / "bin", "prusa-slicer", FAKE_BROKEN)
    monkeypatch.setenv("PATH", str(exe.parent))
    with pytest.raises(PiForgeError, match="not manifold"):
        slice_stl(stl, "generic", "PLA", spaced_tmp / "out")


def test_slicer_writing_nothing_is_an_error_even_with_old_output(no_slicers, monkeypatch,
                                                                 spaced_tmp, stl):
    exe = _install(spaced_tmp / "bin", "prusa-slicer", FAKE_SILENT)
    monkeypatch.setenv("PATH", str(exe.parent))
    out_dir = spaced_tmp / "out"
    out_dir.mkdir()
    (out_dir / "my part.gcode").write_text("; estimated printing time (normal mode) = 9h 0m 0s\n")
    with pytest.raises(PiForgeError, match="no G-code"):
        slice_stl(stl, "generic", "PLA", out_dir)
    assert not (out_dir / "my part.gcode").exists()  # stale output cleared before slicing


def test_missing_stl_rejected(spaced_tmp):
    with pytest.raises(PiForgeError, match="STL"):
        slice_stl(spaced_tmp / "nope.stl", "generic", "PLA", spaced_tmp / "out")


def test_parse_gcode_stats():
    prusa = "\n".join([
        "; generated by PrusaSlicer 2.8.1+MacOS-arm64 on 2026-10-04 at 10:00:00 UTC",
        "G1 X10 Y10",
        "; filament used [mm] = 4123.45",
        "; filament used [cm3] = 9.92",
        "; filament used [g] = 12.00",
        "; filament cost = 0.99",
        "; total filament used [g] = 12.34",
        "; total filament cost = 0.99",
        "; estimated printing time (normal mode) = 1h 2m 3s",
        "; estimated first layer printing time (normal mode) = 1m 5s",
    ])
    s = parse_gcode_stats(prusa)
    assert s["time_s"] == 3723
    assert s["filament_g"] == pytest.approx(12.34)  # the total wins over the per-extruder line
    assert s["filament_m"] == pytest.approx(4.12345)
    assert s["filament_cm3"] == pytest.approx(9.92)
    assert s["cost"] == pytest.approx(0.99)
    assert s["generator"].startswith("PrusaSlicer 2.8.1")

    assert parse_gcode_stats("; filament used [g] = 12.34\n")["filament_g"] == pytest.approx(12.34)
    orca = parse_gcode_stats("; HEADER_BLOCK_START\n; model printing time: 1h 2m 3s\n")
    assert orca["time_s"] == 3723 and orca["model_time_s"] == 3723


def test_parse_gcode_stats_variants():
    both = parse_gcode_stats("; model printing time: 1h 2m 3s; total estimated time: 1h 10m 0s\r\n")
    assert both["time_s"] == 4200 and both["model_time_s"] == 3723
    multi = parse_gcode_stats(
        "; filament used [g] = 1.5, 2.5\n; filament used [mm] = 100.0, 300.0\n"
        "; estimated printing time (normal mode) = 1d 0h 0m 1s\n"
    )
    assert multi["filament_g"] == pytest.approx(4.0) and multi["filament_m"] == pytest.approx(0.4)
    assert multi["time_s"] == 86401
    bambu = parse_gcode_stats("; total filament length [mm] : 2500.0\n; total filament weight [g] : 7.5\n")
    assert bambu["filament_m"] == pytest.approx(2.5) and bambu["filament_g"] == pytest.approx(7.5)
    empty = parse_gcode_stats("G28\nG1 X0\n")
    assert empty["time_s"] is None and empty["filament_g"] is None and empty["filament_m"] is None
