"""Involute spur gears and racks (generated by a virtual rack cutter) + mesh check."""

from __future__ import annotations

import math

import pytest

from piforge.core.errors import ValidationError


def test_gear_geometry():
    from piforge.mech.gears import gear_geometry

    g = gear_geometry(1.0, 20)
    assert g["pitch_d"] == pytest.approx(20.0)
    assert g["base_d"] == pytest.approx(20 * math.cos(math.radians(20)), abs=1e-3)  # 18.794
    assert g["base_d"] == pytest.approx(18.794, abs=1e-3)
    assert g["tip_d"] == pytest.approx(22.0)
    assert g["root_d"] == pytest.approx(17.5)
    assert g["circular_pitch"] == pytest.approx(math.pi)
    assert g["tooth_thickness"] == pytest.approx(math.pi / 2)

    shifted = gear_geometry(2.0, 10, profile_shift=0.5)
    assert shifted["tip_d"] == pytest.approx(2 * (10 + 2 + 1.0))
    assert shifted["tooth_thickness"] == pytest.approx(math.pi + 2 * 0.5 * 2 * math.tan(math.radians(20)))


def test_center_distance_and_validation():
    from piforge.mech.gears import center_distance, gear_geometry

    assert center_distance(1.5, 12, 30) == pytest.approx(31.5)
    with pytest.raises(ValidationError):
        gear_geometry(0, 20)
    with pytest.raises(ValidationError):
        gear_geometry(1, 3)


def test_profile_radii():
    """The generated 2D profile reaches the tip circle and is cut down to the root circle."""
    from piforge.mech.gears import gear_geometry, gear_profile

    for z in (8, 12, 24):
        g = gear_geometry(1.0, z)
        poly = gear_profile(1.0, z, backlash=0.0)
        assert poly.is_valid
        coords = list(poly.exterior.coords)
        radii = [math.hypot(x, y) for x, y in coords]
        assert max(radii) == pytest.approx(g["tip_d"] / 2, abs=0.01)
        assert min(radii) == pytest.approx(g["root_d"] / 2, abs=0.02)


def test_gear_mesh_ok():
    from piforge.mech.gears import check_mesh

    rep = check_mesh(1.0, 12, 24)
    assert not rep.has("GEAR.INTERFERENCE"), rep.to_markdown()
    assert rep.has("GEAR.OK")
    bad = check_mesh(1.0, 12, 24, extra_distance=-0.6)
    assert bad.has("GEAR.INTERFERENCE", "error")


def test_gear_mesh_small_pinion_with_undercut():
    from piforge.mech.gears import check_mesh

    assert not check_mesh(1.0, 8, 40).has("GEAR.INTERFERENCE")


@pytest.mark.slow
def test_spur_gear_solid():
    from piforge.mech.export import to_trimesh
    from piforge.mech.gears import gear_geometry, spur_gear

    g = spur_gear(1.0, 20, 5.0, bore=5.0, hub_d=10.0, hub_h=4.0)
    assert g.is_valid
    bb = g.bounding_box()
    assert bb.min.Z == pytest.approx(0.0, abs=1e-6) and bb.max.Z == pytest.approx(9.0, abs=1e-6)
    assert bb.max.X - bb.min.X == pytest.approx(gear_geometry(1.0, 20)["tip_d"], abs=0.05)
    assert to_trimesh(g).is_watertight


@pytest.mark.slow
def test_rack_solid():
    from piforge.mech.export import to_trimesh
    from piforge.mech.gears import rack

    r = rack(1.0, 50.0, 5.0, 8.0)
    assert r.is_valid
    bb = r.bounding_box()
    assert bb.max.X - bb.min.X == pytest.approx(50.0, abs=1e-6)
    assert bb.max.Y == pytest.approx(9.0, abs=1e-3)  # pitch line at 8 + addendum 1
    assert to_trimesh(r).is_watertight


# --- fix round 1: rack meshing (gear phase relative to the rack teeth) -----------------------
@pytest.mark.parametrize("z", [12, 13, 14, 15, 16, 20])
def test_rack_mesh_location_phase(z):
    from piforge.mech.gears import rack_mesh_location

    m, h = 1.5, 8.0
    p = math.pi * m
    x, y, zz = rack_mesh_location(m, z, h, x_near=30.0).position
    assert y == pytest.approx(h + m * z / 2) and zz == pytest.approx(0.0)
    assert abs(x - 30.0) <= p / 2 + 1e-9
    k = x / p
    if z % 4 == 0:  # a tooth points straight down into a rack tooth space (spaces at k·p)
        assert k == pytest.approx(round(k), abs=1e-9)
    elif z % 4 == 2:  # a tooth space points down onto a rack tooth at (k + ½)·p
        assert k - 0.5 == pytest.approx(round(k - 0.5), abs=1e-9)


@pytest.mark.parametrize("z", [12, 13, 14, 15])
def test_check_rack_mesh_ok_at_location(z):
    from piforge.mech.gears import check_rack_mesh

    rep = check_rack_mesh(1.5, z, 8.0, length=60.0)
    assert not rep.has("GEAR.INTERFERENCE"), rep.to_markdown()
    assert rep.has("GEAR.OK")


def test_check_rack_mesh_wrong_phase_detected():
    """Reviewer probe p2: z=12 at 6.5·p (tooth on tooth) interferes; 6·p meshes."""
    from piforge.mech.gears import check_rack_mesh

    p = math.pi * 1.5
    assert check_rack_mesh(1.5, 12, 8.0, gear_x=6.5 * p, length=60.0).has("GEAR.INTERFERENCE", "error")
    assert not check_rack_mesh(1.5, 12, 8.0, gear_x=6 * p, length=60.0).has("GEAR.INTERFERENCE")
    # too close to the rack also interferes
    assert check_rack_mesh(1.5, 12, 8.0, length=60.0, extra_distance=-0.6).has("GEAR.INTERFERENCE")
